
tasks:
  - init: npm i
    command: npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5173
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - svelte.svelte-vscode